apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs-redis
  template:
    metadata:
      labels:
        app: nestjs-redis
    spec:
      containers:
        - name: app
          image: nestjs-redis:latest  
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_PORT
