apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nestjs-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: nestjs-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
